autoasia/autoasia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoasia/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order, name='order'),
    path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

autoasia/main/urls.py
from django.urls import path
from .views import *
from . import views


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('shop/', shop, name='shop'),
    path('contact/', contact, name='contact'),
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    # path('products/', c, name='contact'),
    path('<int:brand_pk>/', automodels, name='automodels'),
    path('<int:brand_pk>/<int:model_pk>/', category, name='category'),
    path('<int:brand_pk>/<int:model_pk>/<int:category_pk>/', products, name='products'),
    path('product/<int:product_pk>/', product_view, name='product'),
]

autoasia/main/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    depends_on_brands = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')

    def __str__(self):
        return self.name


class Subcategory1(models.Model):
    name = models.CharField(max_length=100)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/', blank=True, null=True)

    def __str__(self):
        return self.name


class Automodel(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Bestproduct(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    price_disc = models.DecimalField(verbose_name='Цена со скидкой', max_digits=7, decimal_places=2, null=True, blank=True)
    new = models.BooleanField(verbose_name='Новый товар')
    date = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Product(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    description = models.CharField(max_length=255, blank=True, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    product_code = models.CharField(max_length=32, blank=True, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, blank=True, null=True)
    subcategory1 = models.ForeignKey(Subcategory1, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    automodel = models.ForeignKey(Automodel, on_delete=models.SET_NULL, blank=True, null=True)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/', blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена', default=0)
    price_disc = models.DecimalField(verbose_name='Цена со скидкой', max_digits=7, decimal_places=2, null=True, blank=True)
    new = models.BooleanField(verbose_name='В наличии', default=False)
    best_product = models.BooleanField(verbose_name='Лучший продукт(продаваемый)', default=False)
    date = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True)

    def __str__(self):
        return self.name


class Applications(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    mail = models.CharField(verbose_name='Почта', max_length=200)
    phone = models.CharField(verbose_name='Номер телефона', max_length=200)
    date = models.DateTimeField(verbose_name='Дата', auto_now_add=True, null=True)

    def __str__(self):
        return self.mail

    class Meta:
        verbose_name = 'Заявка cо страницы контактов'
        verbose_name_plural = 'Заявка со страницы контактов'

autoasia/main/forms.py
from django import forms
from .models import Applications
from django.db import models


class ApplicationsForm(forms.ModelForm):
    class Meta:
        model = Applications
        fields = ['mail', 'name', 'phone']

autoasia/main/views.py
from .models import Bestproduct, Brand, Automodel, Category, Product
from django.shortcuts import render, redirect
from cart.forms import CartAddProductForm
from django.core.mail import send_mail
from .forms import ApplicationsForm
from django.views import View
from cart.cart import Cart
import telebot

bot = telebot.TeleBot("1387522266:AAHTqKbJzHhhwqwsi7-q8oCD-cxKMwj4k04")


def index(request):
    products = Bestproduct.objects.all()
    cart_product_form = CartAddProductForm()
    brands = Brand.objects.all()
    cart = Cart(request)
    context = {
        'best': products,
        'brands': brands,
        'cart': cart,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'main/index.html', context)


def about(request):
    return render(request, 'main/about.html')


def shop(request):
    return render(request, 'main/product.html')


def contact(request):
    return render(request, 'main/contact.html')


def automodels(request, brand_pk):
    automodels = Automodel.objects.filter(brand_id=brand_pk)
    context = {
        'automodels': automodels,
        'brand_pk': brand_pk,
    }
    return render(request, 'main/automodels.html', context)


def category(request, brand_pk, model_pk):
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'brand_pk': brand_pk,
        'model_pk': model_pk,
    }
    return render(request, 'main/categories.html', context)


def products(request, brand_pk, model_pk, category_pk):
    category = Category.objects.filter(id=category_pk)
    if category.exists():
        if not category.first().depends_on_brands:
            products = Product.objects.filter(category_id=category_pk)
        else:
            products = Product.objects.filter(brand_id=brand_pk, automodel_id=model_pk, category_id=category_pk)
    context = {
        'products': products,
        'brand_pk': brand_pk,
        'model_pk': model_pk,
        'category_pk': category_pk,
    }
    return render(request, 'main/products.html', context)


def product_view(request, product_pk):
    brands = Brand.objects.all()
    product = Product.objects.get(id=product_pk)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    context = {
        'cart_product_form': cart_product_form,
        'product_pk': product_pk,
        'product': product,
        'brands': brands,
        'cart': cart,
    }
    return render(request, 'main/product.html', context)


class ApplicationsView(View):
    def post(self, request):
        if request.method == 'POST':
            form = ApplicationsForm(request.POST)
            # print(request.POST)
        if form.is_valid():
            form.save()
            mail = form.cleaned_data['mail']
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            subject = 'Новая заявка!'
            from_email = 'assassinaltair@bk.ru'
            to_email = ['aitofullstackdev@gmail.com', 'aitolivelive@gmail.com']
            message = 'Новая заявка на обратный звонок!' + '\r\n' + '\r\n' + 'Почта: ' + mail + '\r\n' + '\r\n' + 'Имя:' + name + '\r\n' + '\r\n' + 'Номер телефона: ' + phone
            # send_mail(subject, message, from_email, to_email, fail_silently=False)
            bot.send_message(-387514692, message)
        return redirect('main:contact')

autoasia/main/templates/main/automodels.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Модели{% endblock %}
{% block content %}

<body class="common-home res layout-1">
    
    <div id="wrapper" class="wrapper-fluid banners-effect-5">
    

    {% include 'header.html' %}
    
   
<!-- Main Container  -->
<div class="main-container">
    <div id="content">
        <!-- <div class="content-top-w container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 col_slla  box-advanced-search">
                    <div class="so_advanced_search">
                        <div class="sas_wrap">
                            <div class="sas_inner">
                                <div class="heading-title"><h2>Фильтрация</h2></div>
                                <div class="sas_inner-box-search">
                                    <div class="row">
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="make" id="so_make0" class="form-control">
                                                <option value="">Выберите производителя</option>
                                                    <option value="1" >Acura</option>
                                                    <option value="2" >BMW</option>
                                                    <option value="3" >Chevrolet</option>
                                                    <option value="4" >GMC</option>
                                                    <option value="5" >Honda</option>
                                                    <option value="6" >John deere</option>
                                                    <option value="7" >Kawasaky</option>
                                                    <option value="8" >Lexus</option>
                                                    <option value="9" >mazda</option>
                                                    <option value="10" >Mercedes</option>
                                                    <option value="11" >nuko</option>
                                                    <option value="12" >Opel</option>
                                                    <option value="13" >Yamaha</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="model" id="so_model0" class="form-control">
                                                <option value="">Выберите модель</option>
                                                <option value="1" >3D Model</option>
                                                <option value="2" >BMW</option>
                                                <option value="3" >1000 Rocket</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="engine" id="so_engine0" class="form-control">
                                                <option value="">Выберите пакет</option>
                                                <option value="1" >320i</option>
                                                <option value="2" >x5</option>
                                                <option value="3" >350i</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="year" id="so_year0" class="form-control">
                                                <option value="">Выберите год</option>
                                                    <option value="1" >2015</option>
                                                    <option value="2" >2016</option>
                                                    <option value="3" >2017</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-button">
                                            <button type="button" id="sas_search_button0">Найти мою машину!</button>
                                        </div>
                                    </div>              
                                </div>
                            </div>   
                        </div>
                    </div> 
                </div>
                    
            </div>                                   
        </div> -->
        <table style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 60px;" border="0" cols="4"> 
            <tbody> 
               
                <tr style="display: flex; justify-content: space-evenly; flex-wrap: wrap;" class="main-tr"> 
                     {% for model in automodels %}
                    <td style="width: 30%;">
                        <li><a href="{% url 'main:category' brand_pk model.id %}">{{ model.name }}</a></li>
                    </td>
                      {% endfor %} 
                    </tr>  
                    
                </tbody> 
            </table>
        
        </div>
    </div>
</div>
    {% include 'footer.html' %}

    </div>
</body>
{% endblock %}

autoasia/main/templates/main/product.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Продукт | autoasiakg{% endblock %}
{% block content %}


<body class="res layout-subpage layout-1 banners-effect-5 product-details">
    <div id="wrapper" class="wrapper-fluid">
    
    {% include 'header.html' %}
    <!-- //Header Container  -->

    <!-- Main Container  -->
    <div class="main-container container">
        <ul class="breadcrumb">
            <li><a href="{% url 'main:index' %}"><i class="fa fa-home"></i></a></li>
            <li><a href="product-v2.html#">Детальная страница продуктов</a></li>
            <li><a href="product-v2.html#">{{ product.name }}</a></li>
        </ul>
        
        <div class="row">

            <!--Middle Part Start-->
            <div id="content" class="col-md-9 col-sm-8">
                
                <div class="product-view">
                    <div class="left-content-product">
                        <div class="row">
                            <div class="content-product-right col-md-6 col-sm-12 col-xs-12">
                                <div class="title-product">
                                    <h1>{{ product.name }}</h1>
                                </div>
                                <!-- Review ---->
                                

                                <div class="product-label form-group">
                                    <div class="product_page_price price" itemprop="offerDetails" itemscope="" itemtype="http://data-vocabulary.org/Offer">
                                        {% if product.price_disc %}
                                            <span class="price-new" itemprop="price">{{ product.price }} сомов</span>
                                            <span class="price-old">{{ product.price_disc }} сомов</span>
                                        {% else %}
                                            <span class="price-new" itemprop="price">{{ product.price }} сомов</span>
                                        {% endif %}
                                    </div>
                                    <div class="stock"><span>В наличии:</span>
                                        {% if product.new == True %}
                                            <span class="status-stock">В наличии</span>
                                        {% else %}
                                            <span>Нету в наличии</span>
                                        {% endif %}
                                        </div>
                                </div>

                               

                                <div class="short_description form-group">
                                    <h4>Описание продукта:</h4>
                                    {{ product.description }}
                                </div>
                                <div id="product">

                                    <div class="form-group box-info-product">
                                        <form action="{% url 'cart:cart_add' product.id %}" method="POST">
                                        <div class="option quantity">
                                            <div class="input-group quantity-control" unselectable="on" style="-webkit-user-select: none;">
                                                <label>Количество</label>
                                                <input class="form-control" type="text" name="quantity"
                                                value="1">
                                                <input type="hidden" name="product_id" value="50">
                                                <span class="input-group-addon product_quantity_down">−</span>
                                                <span class="input-group-addon product_quantity_up">+</span>
                                                {{ cart_product_form }}
                                                {% csrf_token %}
                                                <input type="submit" value="+ В корзину">
                                            </div>
                                        </div>
                                        </form>
                                        <!-- <div class="cart">
                                            <input type="submit" data-toggle="tooltip" title="" value="В корзину" data-loading-text="Loading..." id="button-cart" class="btn btn-mega btn-lg" onclick="cart.add('42', '1');" data-original-title="В корзину">
                                        </div> -->
                                    </div>

                                </div>
                                <!-- end box info product -->

                            </div>
                        </div>
                    </div>
                    
                
                </div>
                
                <!-- Bestproduct Tabs -->
                <div class="producttab ">
                    <div class="tabsslider horizontal-tabs  col-xs-12">
                        <ul class="nav nav-tabs">
                            <li class="active"><a data-toggle="tab" href="product-v2.html#tab-1">Описание</a></li>
                        </ul>
                        <div class="tab-content col-xs-12">
                            <div id="tab-1" class="tab-pane fade active in">
                                <p>{{ product.description }}</p>
                                
                            </div>
                        </div>
                    </div>
                </div>
                <!-- //Bestproduct Tabs -->
                
                

                <!-- end Related  Bestproducts-->

        

                
            </div>
            <!--Middle Part End-->
            <!--Left Part Start -->
            <aside class="col-sm-4 col-md-3 content-aside" id="column-left">
                <div class="module category-style">
                    <h3 class="modtitle">Категории</h3>
                    <div class="modcontent">
                        <div class="box-category">
                            {% for brand in brands %}
                            <ul id="cat_accordion" class="list-group">
                                <li class=""><a href="{% url 'main:automodels' brand.id %}" class="cutom-parent">{{ brand.name }}</a>  <span class="dcjq-icon"></span></li>
                            </ul>
                            {% endfor %}
                        </div>
                        
                        
                    </div>
                </div>
            </aside>
            <!--Left Part End -->
        </div>
        
    </div>
    <!-- //Main Container -->
    

    {% include 'footer.html' %}

    </div>
    

</div>      

</body>
{% endblock %}

autoasia/main/templates/main/products.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Все продукты{% endblock %}
{% block content %}

<body class="common-home res layout-1">
    
    <div id="wrapper" class="wrapper-fluid banners-effect-5">
    

    {% include 'header.html' %}
    
   
<!-- Main Container  -->
<div class="main-container">
    <div id="content">
        <!-- <div class="content-top-w container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-12 col-xs-12 col_slla  box-advanced-search">
                    <div class="so_advanced_search">
                        <div class="sas_wrap">
                            <div class="sas_inner">
                                <div class="heading-title"><h2>Фильтрация</h2></div>
                                <div class="sas_inner-box-search">
                                    <div class="row">
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="make" id="so_make0" class="form-control">
                                                <option value="">Выберите производителя</option>
                                                    <option value="1" >Acura</option>
                                                    <option value="2" >BMW</option>
                                                    <option value="3" >Chevrolet</option>
                                                    <option value="4" >GMC</option>
                                                    <option value="5" >Honda</option>
                                                    <option value="6" >John deere</option>
                                                    <option value="7" >Kawasaky</option>
                                                    <option value="8" >Lexus</option>
                                                    <option value="9" >mazda</option>
                                                    <option value="10" >Mercedes</option>
                                                    <option value="11" >nuko</option>
                                                    <option value="12" >Opel</option>
                                                    <option value="13" >Yamaha</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="model" id="so_model0" class="form-control">
                                                <option value="">Выберите модель</option>
                                                <option value="1" >3D Model</option>
                                                <option value="2" >BMW</option>
                                                <option value="3" >1000 Rocket</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="engine" id="so_engine0" class="form-control">
                                                <option value="">Выберите пакет</option>
                                                <option value="1" >320i</option>
                                                <option value="2" >x5</option>
                                                <option value="3" >350i</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-boxes">
                                            <select name="year" id="so_year0" class="form-control">
                                                <option value="">Выберите год</option>
                                                    <option value="1" >2015</option>
                                                    <option value="2" >2016</option>
                                                    <option value="3" >2017</option>
                                            </select>
                                        </div>
                                        <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 search-button">
                                            <button type="button" id="sas_search_button0">Найти мою машину!</button>
                                        </div>
                                    </div>              
                                </div>
                            </div>   
                        </div>
                    </div> 
                </div>
                    
            </div>                                   
        </div> -->
        <!-- <table style="width: 80%; margin-left: auto; margin-right: auto; margin-top: 40px;margin-bottom: 10px;" border="0" cols="4"> 
            <tbody> 
               
                <tr style="display: flex; justify-content: space-evenly; flex-wrap: wrap;">
                {% if products and products.count > 0%}
                {% for product in products %}
                        <td style="width: 30%;">
                            <li><a href="{% url 'main:product' product.id %}">{{ product.name }}</a></li>
                        </td>
                    {% endfor %}  
                    {% else %}
                    <h1 style='text-align: center; margin-top: 30px;'>Продуктов нет</h1>
                    {% endif %}
                </tr>
                </tbody> 
            </table>  -->
            <div class="main-wrapper">
                <div class="cart-main-area pt-85 pb-90">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12 col-12">
                                <form action="cart.html#">
                                    <div class="table-content table-responsive cart-table-content">
                                        <table>
                                            <thead>
                                                <tr>
                                                    <th style="padding-left: -20%;">Наименование</th>
                                                    <th>Название продукта</th>
                                                    <th>Цена продукта</th>
                                                    <th>Производство</th>
                                                    <th>Удалить</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                            {% if products and products.count > 0%}
                                                {% for product in products %}
                                                <tr>
                                                    <td class="product-name" style="padding-right: 10%;">
                                                        <a href="cart.html#">{{ product.name }}</a>
                                                    </td>
                                                    <td class="product-brand" style="padding-left: 30px;"><a href="cart.html#">{{ product.brand }}</a></td>
                                                    <td class="product-price-cart" style="padding-left: 30px;"><span class="amount">{{ product.price }}</span></td>
                                                    <td class="product-manufactur" style="padding-left: 30px;"><a href="cart.html#">{{ product.manufacturer }}</a></td>
                                                    <td class="product-remove" style="padding-left: 30px;">
                                                        <a href="{% url 'cart:cart_remove' product.id %}"> <i class="fas fa-cart-plus"></i></a>
                                                    </td>
                                                </tr>
                                            {% endfor %}
                                            {% else %}
                                            <h1 style='text-align: center; margin-top: 30px;'>Продуктов нет</h1>
                                            {% endif %}
                                            </tbody>
                                        </table>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
    {% include 'footer.html' %}

    </div>
</body>
{% endblock %}