autoasia/autoasia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoasia/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order, name='order'),
    path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

autoasia/main/urls.py
from django.urls import path
from .views import *
from . import views


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('shop/', shop, name='shop'),
    path('contact/', contact, name='contact'),
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    # path('products/', c, name='contact'),
    path('<int:brand_pk>/', automodels, name='automodels'),
    path('<int:brand_pk>/<int:model_pk>/', category, name='category'),
    path('<int:brand_pk>/<int:model_pk>/<int:category_pk>/', products, name='products'),
    path('product/<int:product_pk>/', product_view, name='product'),
]

autoasia/cart/models.py
from django.db import models

# Create your models here.

autoasia/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOISES = [(i, str(i)) for i in range(1, 100)]


# class CartAddBestproductForm(forms.Form):
#     quantity = forms.CharField(required=False, initial=1, widget=forms.HiddenInput)
#     update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class CartAddProductForm(forms.Form):
    quantity = forms.CharField(required=False, initial=1, widget=forms.HiddenInput)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)
    
class OrderSendForm(forms.Form):
    phone = forms.CharField()

autoasia/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from main.models import Bestproduct, Product
from django.views import View
from .cart import Cart
import telebot
from .forms import CartAddProductForm, OrderSendForm

#1387522266:AAHTqKbJzHhhwqwsi7-q8oCD-cxKMwj4k04
bot = telebot.TeleBot("1387522266:AAHTqKbJzHhhwqwsi7-q8oCD-cxKMwj4k04")


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product,  id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
            initial={'quantity': item['quantity'],
                     'update': True})
    context = {
        'cart': cart
    }
    return render(request, 'cart/cart.html', context)


def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')


def order(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/checkout.html', context)


class OrderSendView(View):
    def post(self, request):
        if request.method == 'POST':
            form = OrderSendForm(request.POST)
            if form.is_valid():
                phone = form.cleaned_data['phone']
                cart = Cart(request)
                message = 'Поступил новый заказ!\r\n\r\nТелефон: ' + phone + '\r\n'  + '\r\n\r\nПродукты\r\n\r\n'

                for c in cart:
                    message += 'Название: ' + str(c['product']) + '\r\n'
                    message += 'Цена: ' + str(c['price']) + '\r\n\r\n'
                    message += 'Количество: ' + str(c['quantity']) + '\r\n\r\n'

                message += 'Общая стоимость: ' + str(cart.get_total_price())

                bot.send_message(-387514692, message)
                Cart.clear(cart)
                return redirect('main:index')
            return redirect('main:index')

autoasia/cart/templates/cart/cart.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Корзина{% endblock %}
{% block content %}

<body class="res layout-1">
    
    <div id="wrapper" class="wrapper-fluid banners-effect-5">
    

    {% include 'header.html' %}
    
	<!-- Main Container  -->
	<div class="main-container container">
		<ul class="breadcrumb">
			<li><a href="cart.html#"><i class="fa fa-home"></i></a></li>
			<li><a href="cart.html#">Shopping Cart</a></li>
		</ul>
		
		<div class="row">
			<!--Middle Part Start-->
        <div id="content" class="col-sm-12">
          <h2 class="title">Shopping Cart</h2>
            <div class="table-responsive form-group">
              <table class="table table-bordered">
                <thead>
                  <tr>
                    <td class="text-center">Image</td>
                    <td class="text-left">Bestproduct Name</td>
                    <td class="text-left">Model</td>
                    <td class="text-left">Quantity</td>
                    <td class="text-right">Unit Price</td>
                    <td class="text-right">Total</td>
                  </tr>
                </thead>
                <tbody>
                	{% if cart %}
                        {% for item in cart %}
                            {% with product=item.product %}
                  <tr>
                    <td class="text-center"><a href="product.html">
                      {% if product.img %}
                      <img width="70px" src="{{ product.img.url }}" alt="Aspire Ultrabook Laptop" title="Aspire Ultrabook Laptop" class="img-thumbnail" />
                      {% endif %}
                    </a></td>
                      }
                    <td class="text-left"><a href="product.html">{{ product.name }}</a><br />
                     </td>
                    <td class="text-left">По умолчанию</td>
                    <td class="text-left" width="200px"><div class="input-group btn-block quantity">
                        <input type="text" name="quantity" value="1" size="1" class="form-control" />
                        <span class="input-group-btn">
                        <button type="submit" data-toggle="tooltip" title="Update" class="btn btn-primary"><i class="fa fa-clone"></i></button>
                        <button type="button" data-toggle="tooltip" title="Remove" class="btn btn-danger" onClick=""><i class="fa fa-times-circle"></i></button>
                        </span></div></td>
                    <td class="text-right">{{ item.price }} сомов</td>
                    <td class="text-right">{{ item.total_price }} сомов</td>
                  </tr>
                 
                          	{% endwith %}
                        {% endfor %}
                    {% else %}
                        <td colspan="6" class="product-price-cart"><span class="amount">Корзина пуста.</span>
                    {% endif %}
                </tbody>
              </table>
            </div>
          
		
		
		<div class="row">
			<div class="col-sm-4 col-sm-offset-8">
				<table class="table table-bordered">
					<tbody>
						<tr>
							<td class="text-right">
								<strong>Общая сумма:</strong>
							</td>
							<td class="text-right">{{ cart.get_total_price }}</td>
						</tr>
					</tbody>
				</table>
			</div>
		</div>

		 <div class="buttons">
            <div class="pull-left"><a href="{% url 'main:index' %}" class="btn btn-primary">Продолжить покупки</a></div>
            <div class="pull-right"><a href="order" class="btn btn-primary">Оформить</a></div>
          </div>
        </div>
        <!--Middle Part End -->
			
		</div>
	</div>
	<!-- //Main Container -->
	

	{% include 'footer.html' %}

    </div>
	
	
{% endblock %} 

autoasia/cart/templates/cart/checkout.html
{% extends 'wrapper.html' %}
{% load static %}
{% block title %}Форма{% endblock %}
{% block content %}

<body class="res layout-1">
    
    <div id="wrapper" class="wrapper-fluid banners-effect-5">
    

    {% include 'header.html' %}
    
	<!-- Main Container  -->
	<div class="main-container container">
		<ul class="breadcrumb">
			<li><a href="checkout.html#"><i class="fa fa-home"></i></a></li>
			<li><a href="checkout.html#">Checkout</a></li>
			
		</ul>
		
		<div class="row">
			<!--Middle Part Start-->
			<div id="content" class="col-sm-12">
			  <h2 class="title">Checkout</h2>
			  <div class="so-onepagecheckout row">
				<div class="col-left col-sm-3">
				  <div class="panel panel-default">
					
				  </div>
				  <div class="panel panel-default">
					  <div class="panel-body">
					  	<form action="{% url 'cart:ordersend' %}" method="POST">
							<fieldset id="account">
								{% csrf_token %}
							  <!-- <div class="form-group required">
								<label for="input-payment-firstname" class="control-label">Имя</label>
								<input type="text" class="form-control" id="input-payment-firstname" placeholder="Ваше имя" value="" name="name">
							  </div> -->
							  <!-- <div class="form-group required">
								<label for="input-payment-email" class="control-label">Электронная почта</label>
								<input type="text" class="form-control" id="input-payment-email" placeholder="Электронная почта" value="" name="mail">
							  </div> -->
							  <div class="form-group required">
								<label for="input-payment-telephone" class="control-label">Номер телефона</label>
								<input type="text" class="form-control" id="input-payment-telephone" placeholder="Телефон" value="" name="phone">
							  </div>
							</fieldset>
							<div class="pull-right">
								<input type="submit" class="btn btn-primary" id="button-confirm" value="Подтвердить">
							  </div>
						</form>
						</div>
				  </div>
				  
				</div>
				<div class="col-right col-sm-9">
				  <div class="row">
					
					
					
					
					
					<div class="col-sm-12">
					  <div class="panel panel-default">
						<div class="panel-heading">
						  <h4 class="panel-title"><i class="fa fa-shopping-cart"></i> Shopping cart</h4>
						</div>
						  <div class="panel-body">
							<div class="table-responsive">
							  <table class="table table-bordered">
								<thead>
								  <tr>
									<td class="text-center">Image</td>
									<td class="text-left">Bestproduct Name</td>
									<td class="text-left">Quantity</td>
									<td class="text-right">Unit Price</td>
									<td class="text-right">Total</td>
								  </tr>
								</thead>
								<tbody>
								{% if cart %}
                        		{% for item in cart %}
                            	{% with product=item.product %}
								  <tr>
									<td class="text-center"><a href="product.html">
										{% if product.img %}
										<img width="60px" src="{{ product.img.url }}" alt="Xitefun Causal Wear Fancy Shoes" title="Xitefun Causal Wear Fancy Shoes" class="img-thumbnail">
										{% endif %}
									</a></td>
									<td class="text-left"><a href="product.html">{{ product.name }}	</a></td>
									<td class="text-left"><div class="input-group btn-block" style="min-width: 100px;">
										<input type="text" name="quantity" value="1" size="1" class="form-control">
										<span class="input-group-btn">
										<button type="submit" data-toggle="tooltip" title="Update" class="btn btn-primary"><i class="fa fa-refresh"></i></button>
										<button type="button" data-toggle="tooltip" title="Remove" class="btn btn-danger" onClick=""><i class="fa fa-times-circle"></i></button>
										</span></div></td>
									<td class="text-right">{{ item.price }} сомов</td>
									<td class="text-right">{{ item.total_price }} сомов</td>
								  </tr>
								  		{% endwith %}
			                        {% endfor %}
			                    {% else %}
			                        <td colspan="6" class="product-price-cart"><span class="amount">Корзина пуста.</span>
			                    {% endif %}
								</tbody>
								<tfoot>
								  <tr>
									<td class="text-right" colspan="4"><strong>Общая сумма:</strong></td>
									<td class="text-right">{{ cart.get_total_price }}</td>
								  </tr>
								 
								</tfoot>
							  </table>
							  <div class="buttons">
							</div>
							</div>
						  </div>
					  </div>
					</div>
				  </div>
				</div>
			  </div>
			</div>
			<!--Middle Part End -->
			
		</div>
	</div>
	<!-- //Main Container -->
	
	{% include 'footer.html' %}

    </div>
	

		
{% endblock %} 