autoasia/autoasia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoasia/cart/urls.py
from django.urls import path
from . import views


app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('order/', views.order, name='order'),
    path('order/send/', views.OrderSendView.as_view(), name='ordersend'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

autoasia/main/urls.py
from django.urls import path
from .views import *
from . import views


app_name = 'main'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('shop/', shop, name='shop'),
    path('contact/', contact, name='contact'),
    path('applications/', views.ApplicationsView.as_view(), name='applications'),
    # path('products/', c, name='contact'),
    path('<int:brand_pk>/', automodels, name='automodels'),
    path('<int:brand_pk>/<int:model_pk>/', category, name='category'),
    path('<int:brand_pk>/<int:model_pk>/<int:category_pk>/', products, name='products'),
    path('product/<int:product_pk>/', product_view, name='product'),
]

autoasia/main/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=100)
    depends_on_brands = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Subcategory(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='subcategories')

    def __str__(self):
        return self.name


class Subcategory1(models.Model):
    name = models.CharField(max_length=100)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Brand(models.Model):
    name = models.CharField(max_length=100)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/', blank=True, null=True)

    def __str__(self):
        return self.name


class Automodel(models.Model):
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Bestproduct(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/')
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена')
    price_disc = models.DecimalField(verbose_name='Цена со скидкой', max_digits=7, decimal_places=2, null=True, blank=True)
    new = models.BooleanField(verbose_name='Новый товар')
    date = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Product(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    description = models.CharField(max_length=255, blank=True, null=True)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.SET_NULL, blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    product_code = models.CharField(max_length=32, blank=True, null=True)
    subcategory = models.ForeignKey(Subcategory, on_delete=models.SET_NULL, blank=True, null=True)
    subcategory1 = models.ForeignKey(Subcategory1, on_delete=models.SET_NULL, blank=True, null=True)
    brand = models.ForeignKey(Brand, on_delete=models.SET_NULL, blank=True, null=True)
    automodel = models.ForeignKey(Automodel, on_delete=models.SET_NULL, blank=True, null=True)
    img = models.ImageField(verbose_name='Изображение', upload_to='static/img/bestproduct/', blank=True, null=True)
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name='Цена', default=0)
    price_disc = models.DecimalField(verbose_name='Цена со скидкой', max_digits=7, decimal_places=2, null=True, blank=True)
    new = models.BooleanField(verbose_name='В наличии', default=False)
    best_product = models.BooleanField(verbose_name='Лучший продукт(продаваемый)', default=False)
    date = models.DateTimeField(verbose_name='Дата добавления', auto_now_add=True)

    def __str__(self):
        return self.name


class Applications(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=200)
    mail = models.CharField(verbose_name='Почта', max_length=200)
    phone = models.CharField(verbose_name='Номер телефона', max_length=200)
    date = models.DateTimeField(verbose_name='Дата', auto_now_add=True, null=True)

    def __str__(self):
        return self.mail

    class Meta:
        verbose_name = 'Заявка cо страницы контактов'
        verbose_name_plural = 'Заявка со страницы контактов'

autoasia/main/forms.py
from django import forms
from .models import Applications
from django.db import models


class ApplicationsForm(forms.ModelForm):
    class Meta:
        model = Applications
        fields = ['mail', 'name', 'phone']

autoasia/main/views.py
from .models import Bestproduct, Brand, Automodel, Category, Product
from django.shortcuts import render, redirect
from cart.forms import CartAddProductForm
from django.core.mail import send_mail
from .forms import ApplicationsForm
from django.views import View
from cart.cart import Cart
import telebot

bot = telebot.TeleBot("1387522266:AAHTqKbJzHhhwqwsi7-q8oCD-cxKMwj4k04")


def index(request):
    products = Bestproduct.objects.all()
    cart_product_form = CartAddProductForm()
    brands = Brand.objects.all()
    cart = Cart(request)
    context = {
        'best': products,
        'brands': brands,
        'cart': cart,
        'cart_product_form': cart_product_form,
    }
    return render(request, 'main/index.html', context)


def about(request):
    return render(request, 'main/about.html')


def shop(request):
    return render(request, 'main/product.html')


def contact(request):
    return render(request, 'main/contact.html')


def automodels(request, brand_pk):
    automodels = Automodel.objects.filter(brand_id=brand_pk)
    context = {
        'automodels': automodels,
        'brand_pk': brand_pk,
    }
    return render(request, 'main/automodels.html', context)


def category(request, brand_pk, model_pk):
    categories = Category.objects.all()
    context = {
        'categories': categories,
        'brand_pk': brand_pk,
        'model_pk': model_pk,
    }
    return render(request, 'main/categories.html', context)


def products(request, brand_pk, model_pk, category_pk):
    category = Category.objects.filter(id=category_pk)
    if category.exists():
        if not category.first().depends_on_brands:
            products = Product.objects.filter(category_id=category_pk)
        else:
            products = Product.objects.filter(brand_id=brand_pk, automodel_id=model_pk, category_id=category_pk)
    context = {
        'products': products,
        'brand_pk': brand_pk,
        'model_pk': model_pk,
        'category_pk': category_pk,
    }
    return render(request, 'main/products.html', context)


def product_view(request, product_pk):
    brands = Brand.objects.all()
    product = Product.objects.get(id=product_pk)
    cart_product_form = CartAddProductForm()
    cart = Cart(request)
    context = {
        'cart_product_form': cart_product_form,
        'product_pk': product_pk,
        'product': product,
        'brands': brands,
        'cart': cart,
    }
    return render(request, 'main/product.html', context)


class ApplicationsView(View):
    def post(self, request):
        if request.method == 'POST':
            form = ApplicationsForm(request.POST)
            # print(request.POST)
        if form.is_valid():
            form.save()
            mail = form.cleaned_data['mail']
            name = form.cleaned_data['name']
            phone = form.cleaned_data['phone']
            subject = 'Новая заявка!'
            from_email = 'assassinaltair@bk.ru'
            to_email = ['aitofullstackdev@gmail.com', 'aitolivelive@gmail.com']
            message = 'Новая заявка на обратный звонок!' + '\r\n' + '\r\n' + 'Почта: ' + mail + '\r\n' + '\r\n' + 'Имя:' + name + '\r\n' + '\r\n' + 'Номер телефона: ' + phone
            # send_mail(subject, message, from_email, to_email, fail_silently=False)
            bot.send_message(-387514692, message)
        return redirect('main:contact')

autoasia/main/templates/footer.html
{% load static %}
 <!-- Footer Container -->
    <footer class="footer-container typefooter-1">
        <!-- Footer Top Container -->
        <!-- Footer middle Container -->
        <div class="container">
            <div class="row footer-middle">
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12 col-style">
                    <div class="box-footer box-infos">
                        <div class="module">
                            <h3 class="modtitle">Связаться с нами</h3>
                            <div class="modcontent">
                                <ul class="list-icon">
                                    <li><i class="fas fa-map-marker-alt"></i><a href="https://2gis.kg/bishkek/firm/70000001023398167?m=74.528065%2C42.875423%2F17">    Патриса Лумумбы 8, 1 этаж</a> </li>
                                    <li><i class="fas fa-phone"></i>      <a href="tel:+9960505888181">  0505888181</a></li>
                                    <li><i class="fas fa-envelope"></i>     <a href="mailto:info@autoasia.kg">   info@autoasia.kg</a></li>
                                    <li><i class="fas fa-business-time"></i>   7 дней в неделю</li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 col-style">
                    <div class="row">
                        <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12 col-style">
                            <div class="box-information box-footer">
                                <div class="module clearfix">
                                    <h3 class="modtitle">Информация</h3>
                                    <div class="modcontent">
                                        <ul class="menu">
                                            <li><a href="{% url 'main:index' %}">Главная</a></li>
                                            <li><a href="{% url 'main:about' %}">О нас</a></li>
                                            <li><a href="{% url 'cart:cart_detail' %}">Корзина</a></li>
                                            <li><a href="{% url 'main:contact' %}">Контакты</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row row-dark">
                <div class="col-lg-4 col-md-5 col-sm-5 col-xs-12 col-socials">
                    <ul class="socials">
                       <li class="facebook"><a href="https://www.facebook.com/autoasia.kg" target="_blank"><i class="fab fa-facebook-f"></i></a></li>
                                <li class="phone"><a href="tel:+9960505888181" target="_blank"><i class="fa fa-phone"></i></a></li>
                                <li class="whatsapp"><a href="https://wa.me/+9960505888181" target="_blank"><i class="fa fa-whatsapp"></i></a></li>
                                <li class="instagram"><a href="https://www.instagram.com/autoasiakg/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /Footer middle Container -->
        <!-- Footer Bottom Container -->
        <div class="footer-bottom">        
            <div class="container">
                <div class="row">
                    <div class="copyright col-lg-8 col-md-8 col-sm-12 col-xs-12">
                        <p>Autoasia © 2020 магазин. All Rights Reserved. Все права защищены</p>
                    </div>   
                </div>
            </div>            
        </div>
        <!-- /Footer Bottom Container -->
        
        
            <!--Back To Top-->
        <div class="back-to-top"><i class="fa fa-angle-up"></i></div>
    </footer>
    <!-- //end Footer Container -->

autoasia/main/templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Basic page needs
    ============================================ -->
    <title>{% block title %}TITLE NOT FOUND{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="html5 template, best html5 template, best html template, html5 basic template, multipurpose html5 template, multipurpose html template, creative html templates, creative html5 templates" />
    <meta name="description" content="SuperMarket is a powerful Multi-purpose HTML5 Template with clean and user friendly design. It is definite a great starter for any eCommerce web project." />
    <meta name="author" content="Magentech">
    <meta name="robots" content="index, follow" />
   
    <!-- Mobile specific metas
    ============================================ -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
    <!-- Favicon
    ============================================ -->
    <link rel="shortcut icon" type="image/png" href="{% static 'ico/favicon-16x16.png' %}"/>
  
   
    <!-- Libs CSS
    ============================================ -->
    <link rel="stylesheet" href="{% static 'css/bootstrap/css/bootstrap.min.css' %}">
    <link href="{% static 'css/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/datetimepicker/bootstrap-datetimepicker.min.css' %}" rel="stylesheet">
    <link href="{% static 'js/owl-carousel/owl.carousel.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/lib.css' %}" rel="stylesheet">
    <link href="{% static 'js/jquery-ui/jquery-ui.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/adaptive.css' %}">
    <link href="{% static 'js/minicolors/miniColors.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link href="{% static 'js/pe-icon-7-stroke/css/pe-icon-7-stroke.css' %}" rel="stylesheet">
    <link href="https://demo.smartaddons.com/templates/html/autoparts/pe-icon-7-stroke/css/helper.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/vendor/bootstrap.min.css' %}">
    <!-- Icon Font CSS -->
    <link rel="stylesheet" href="{% static 'css/vendor/line-awesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/vendor/themify.css' %}">
    <!-- Theme CSS
    ============================================ -->
    <link href="{% static 'css/themecss/so_searchpro.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/so_megamenu.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/so_advanced_search.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/so-listing-tabs.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/so-categories.cs' %}s" rel="stylesheet">
    <link href="{% static 'css/themecss/so-newletter-popup.css' %}" rel="stylesheet">
    <link href="{% static 'css/themecss/so-latest-blog.css' %}" rel="stylesheet">

    <link href="{% static 'css/footer/footer1.css' %}" rel="stylesheet">
    <link href="{% static 'css/header/header1.css' %}" rel="stylesheet">
    <link id="color_scheme" href="{% static 'css/theme.css' %}" rel="stylesheet"> 
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
    <script src='https://kit.fontawesome.com/c8e4d183c2.js' crossorigin="anonymous"></script>
    

     <!-- Google web fonts
    ============================================ -->
    <link href='https://fonts.googleapis.com/css?family=Rubik:300,400,400i,500,600,700' rel='stylesheet' type='text/css'>     
    <style type="text/css">
         body{font-family:'Rubik', sans-serif;}
    </style>

</head>
{% block content %}

{% endblock %}
<!-- Include Libs & Plugins
============================================ -->
<!-- Placed at the end of the document so the pages load faster -->
<script type="text/javascript" src="{% static 'js/jquery-2.2.4.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/owl-carousel/owl.carousel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/slick-slider/slick.js' %}"></script>
<script type="text/javascript" src="{% static 'js/themejs/libs.js' %}"></script>
<script type="text/javascript" src="{% static 'js/unveil/jquery.unveil.js' %}"></script>
<script type="text/javascript" src="{% static 'js/countdown/jquery.countdown.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/dcjqaccordion/jquery.dcjqaccordion.2.8.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/datetimepicker/moment.js' %}"></script>
<script type="text/javascript" src="{% static 'js/datetimepicker/bootstrap-datetimepicker.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery-ui/jquery-ui.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/modernizr/modernizr-2.6.2.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/minicolors/jquery.miniColors.min.js' %}"></script>

<script type="text/javascript" src="{% static 'js/lightslider/lightslider.js' %}"></script>

<!-- Theme files
============================================ -->

<script type="text/javascript" src="{% static 'js/themejs/application.js' %}"></script>

<script type="text/javascript" src="{% static 'js/themejs/homepage.js' %}"></script>

<script type="text/javascript" src="{% static 'js/themejs/toppanel.js' %}"></script>
<script type="text/javascript" src="{% static 'js/themejs/so_megamenu.js' %}"></script>
<script type="text/javascript" src="{% static 'js/themejs/addtocart.js' %}"></script>  

<!-- <script type="text/javascript" src="js/themejs/cpanel.js"></script> -->

</html>